### ISSUE TITLE
Submissions List doesn't submit automatically

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/WaterReporter-Android#1]
The Submission List needs to submit automatically for the user if there are un-submitted Reports in the list (reports without a checkmark beside them).

If auto submitting the un-submitted reports is too much, we can talk about a plan b that would include a Toast message, but the auto-submit would be the preferred solution.

**Comment by ryanhamley** [comment]
I added automatic submission when the list view is shown. There's a check to make sure that it can't overlap with pull to refresh. I also added a loading animation for automatic submission and a check so that the "All reports submitted" toast doesn't show every time the list is built (i.e. every time the screen orientation changes) and only when the list is submitted from pull to refresh.
