### ISSUE TITLE
GPS Working Intermittently 

### ISSUE THREAD

**Issue by joshuapowell** [WaterReporter/WaterReporter-Android#3]
The GPS functionality is working on some devices, but I noticed that on the Nexus 5 the GPS is not working at all now. This seems to be a new bug that appeared after store submission.

**Comment by ryanhamley** [comment]
I changed a few things:
1. I dropped the distance changed required to launch a new location request from 100 meters to 20 meters. This should still help to preserve battery life by not just constantly requesting updates, but it should be a little more responsive as well. 
2. I added a default center of Washington D.C. that the app should use if it can't locate you. This should prevent the map from initializing in the Atlantic Ocean near Africa and at least give users some familiar reference points instead of a black screen.
3. I added the set center function into the flow that launches the sign-in dialog. The major problem seems to have been that the sign-in dialog would interrupt the lifecycle of the map before a location could be set leading to the default location being set in the ocean.

These changes should most of the problems with location, but we may still want to add a Find Me button that automatically locates the user and centers their position on the map.
